### ISSUE TITLE
Find a way to get `txHash` and use it 

### ISSUE THREAD

**Issue by TheLubab** [curaOS/subgraph#7]
https://github.com/curaOS/subgraph/blob/7d38d481c42f94c874e295128fa6309138484832/src/utils/helpers.ts#L18-L22

**Comment by bestatigen** [comment]
This is important cause right now, clicking on `HISTORY` item while exploring NFTs leads to a broken link on NEAR's explorer.
If I get it correctly, we use the receipt instead of the tx hash. I'm not sure how to retrieve the tx that executes, being that The Graph picks events from logs, so that's picked before there is a tx hash?

**Comment by bestatigen** [comment]
There is a way to retrieve tx hash from receipt id, NEAR explorer is doing it and it can be done by querying RPC node that NEAR maintains. At the moment we just link to block, and will target this as a minor fix after release.
